### ISSUE TITLE
Where your EFI folder?

### ISSUE THREAD

**Issue by Micael106** [RobyRew/Lenovo-Ideapad-Flex-5-14IlL05-Hackintosh#1]
I have a similar laptop, but with i5 10th generation. Can you publish your EFI folder? I am issuing a big problem to boot.

**Comment by RobyRew** [comment]
ETA: This Weekend

**Comment by bhaskaranjana** [comment]
Hello Roby,
I recently got a flex 5 14IIL05.

I have experience with hackintoshing in past.

I tried everything I could (didn't sleep for two days) but I can't get the Mac os Installer to boot. Upon selecting the (external) dmg option in open core boot menu, I get an error known as [EB|#LOG:EXITBS:START].
I tried all the troubleshooting from dortania's guide[](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start)  but I'm stuck on this.
![PXL_20211106_024126617](https://user-images.githubusercontent.com/32594474/140598303-fa7d0fe5-d26f-4261-8e46-6f8a6fc5f1dc.jpg)

Can you tell me how are you progressing? 

If you could, please add me on instagram so that we could discuss with ease. My username is _thekeep3r_

My specs
proc - 5 1035G1
Ssd - Samsung
Intel wifi 6

Should be the same model

**Comment by RobyRew** [comment]
> Hello Roby,
> 
> I recently got a flex 5 14IIL05.
> 
> 
> 
> I have experience with hackintoshing in past.
> 
> 
> 
> I tried everything I could (didn't sleep for two days) but I can't get the Mac os Installer to boot. Upon selecting the (external) dmg option in open core boot menu, I get an error known as [EB|#LOG:EXITBS:START].
> 
> I tried all the troubleshooting from dortania's guide[](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/extended/kernel-issues.html#stuck-on-eb-log-exitbs-start)  but I'm stuck on this.
> 
> ![PXL_20211106_024126617](https://user-images.githubusercontent.com/32594474/140598303-fa7d0fe5-d26f-4261-8e46-6f8a6fc5f1dc.jpg)
> 
> 
> 
> Can you tell me how are you progressing? 
> 
> 
> 
> If you could, please add me on instagram so that we could discuss with ease. My username is _thekeep3r_
> 
> 
> 
> My specs
> 
> proc - 5 1035G1
> 
> Ssd - Samsung
> 
> Intel wifi 6
> 
> 
> 
> Should be the same model

Hello man, I don't have Instagram.
And a bad notice, It would not be possible to release any EFI this weekend for personal reasons.

I hope next week I'll be better.

**Comment by Micael106** [comment]
> Hello Roby, I recently got a flex 5 14IIL05.
> 
> I have experience with hackintoshing in past.
> 
> I tried everything I could (didn't sleep for two days) but I can't get the Mac os Installer to boot. Upon selecting the (external) dmg option in open core boot menu, I get an error known as [EB|#LOG:EXITBS:START]. I tried all the troubleshooting from dortania's guide but I'm stuck on this. ![PXL_20211106_024126617](https://user-images.githubusercontent.com/32594474/140598303-fa7d0fe5-d26f-4261-8e46-6f8a6fc5f1dc.jpg)
> 
> Can you tell me how are you progressing?
> 
> If you could, please add me on instagram so that we could discuss with ease. My username is _thekeep3r_
> 
> My specs proc - 5 1035G1 Ssd - Samsung Intel wifi 6
> 
> Should be the same model

I finally got it to work with Big Sur, i think we have the same laptop: [Lenovo Ideapad Flex 5 14IIL05](https://github.com/Micael106/Lenovo-Ideapad-Flex-5-14IIL05).

**Comment by bhaskaranjana** [comment]
> > Hello Roby, I recently got a flex 5 14IIL05.
> > I have experience with hackintoshing in past.
> > I tried everything I could (didn't sleep for two days) but I can't get the Mac os Installer to boot. Upon selecting the (external) dmg option in open core boot menu, I get an error known as [EB|#LOG:EXITBS:START]. I tried all the troubleshooting from dortania's guide but I'm stuck on this. ![PXL_20211106_024126617](https://user-images.githubusercontent.com/32594474/140598303-fa7d0fe5-d26f-4261-8e46-6f8a6fc5f1dc.jpg)
> > Can you tell me how are you progressing?
> > If you could, please add me on instagram so that we could discuss with ease. My username is _thekeep3r_
> > My specs proc - 5 1035G1 Ssd - Samsung Intel wifi 6
> > Should be the same model
> 
> I finally got it to work with Big Sur, i think we have the same laptop: [Lenovo Ideapad Flex 5 14IIL05](https://github.com/Micael106/Lenovo-Ideapad-Flex-5-14IIL05).

Omg really!!! Yes we have the same laptop. 😍😍
You are a god!!! Can we contact somehow? I need the EFI and compare ! 🥺🥺

**Comment by Micael106** [comment]
Check my my repository: https://github.com/Micael106/Lenovo-Ideapad-Flex-5-14IIL05
